<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://student.com/report"
           targetNamespace="http://student.com/report"
           elementFormDefault="qualified">

    <xs:element name="StudentReportRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="studentId" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="StudentReportResponse">
        <xs:complexType>
            <xs:sequence>
            	<xs:element name="studentId" type="xs:int"/>
                <xs:element name="pdfBase64" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

<!-- XSD define XML format
Request one integer input: studentId
Response one string returned : pdfBase64
Base64 : encode binary files as text
 -->